const services = [
  ["01", "Web & Web App Development", "Fast, accessible websites and business applications designed to convert visitors and simplify operations."],
  ["02", "Mobile App Development", "Intuitive Android, iOS and cross-platform apps built around your customers and business goals."],
  ["03", "Custom Software Solutions", "Purpose-built software that replaces manual work, connects teams and grows with your organisation."],
  ["04", "AI, Automation & Smart Solutions", "Practical AI and workflow automation that reduce repetitive tasks and turn data into action."],
  ["05", "Cloud & Digital Solutions", "Secure, resilient cloud architecture, migration and modernisation for dependable digital services."],
  ["06", "API & System Integration", "Reliable integrations that connect payments, platforms, data and third-party services into one workflow."],
  ["07", "E-commerce & Business Portals", "Secure storefronts and portals with payments, inventory, customer journeys and admin control."],
  ["08", "Product Development & Implementation", "From discovery and prototype to launch, we turn product ideas into production-ready solutions."],
  ["09", "Software Support & Maintenance", "Proactive monitoring, upgrades, performance improvements and responsive technical support."],
];
const industries = ["Education & EdTech", "Legal & Professional Services", "Retail & E-commerce", "Startups & SaaS", "Healthcare", "Social Impact"];

export default function Home() { return <main>
  <header className="nav-wrap"><nav className="nav container" aria-label="Primary navigation"><a href="#top" className="brand" aria-label="Emplementer home"><img src="/logo-emplementer.png" alt="Emplementer software development and solution provider" /></a><div className="nav-links"><a href="#services">Services</a><a href="#about">About</a><a href="#process">Process</a><a href="#contact" className="nav-cta">Start a project</a></div></nav></header>
  <section id="top" className="split-hero" aria-labelledby="hero-title"><div className="container split-hero-inner"><div className="split-hero-copy"><p className="eyebrow">Software development & solution provider</p><h1 id="hero-title">We implement <span>ideas to reality.</span></h1><p>Emplementer turns your vision into secure, scalable and user-friendly digital products—from strategy and design to development, launch and support.</p><div className="hero-actions"><a className="button primary" href="#contact">Discuss your idea <span>↗</span></a><a className="button secondary" href="#services">Explore services</a></div><div className="trust-row"><span>Strategy</span><i>•</i><span>Design</span><i>•</i><span>Development</span><i>•</i><span>Implementation</span></div></div><div className="split-hero-visual" role="img" aria-label="Emplementer turns ideas into digital solutions"><img src="/emplementer-banner-v4.jpg" width="1942" height="809" decoding="async" fetchPriority="high" alt="" /></div></div></section>
  <section className="intro" id="about"><div className="container split"><div><p className="section-label">Your end-to-end technology partner</p><h2>More than code.<br/>A solution that works.</h2></div><div className="intro-copy"><p>Great software begins with a clear understanding of the real problem. We collaborate with founders, businesses and organisations to shape the right solution—then design, build and implement it with care.</p><p>Whether you need a first digital product or want to modernise an established system, we bring together product thinking, engineering and dependable delivery.</p></div></div><div className="container proof-grid"><article><strong>End-to-end</strong><span>From idea and planning to launch and support</span></article><article><strong>Built to scale</strong><span>Reliable foundations for long-term growth</span></article><article><strong>User-first</strong><span>Simple experiences people enjoy using</span></article><article><strong>Transparent</strong><span>Clear communication at every milestone</span></article></div></section>
  <section id="services" className="services-section"><div className="container section-head"><div><p className="section-label">What we build</p><h2>Digital solutions with<br/><em>real impact.</em></h2></div><p>Focused technology services for every stage of your digital journey.</p></div><div className="container services-grid">{services.map(([n,title,desc]) => <article className="service-card" key={n}><span className="service-no">{n}</span><h3>{title}</h3><p>{desc}</p><a href="#contact" aria-label={`Discuss ${title}`}>Let’s talk <span>↗</span></a></article>)}</div></section>
  <section className="industries"><div className="container"><p className="section-label">Industry experience</p><h2>Technology shaped around<br/>your world.</h2><div className="industry-list">{industries.map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></div></section>
  <section id="process" className="process"><div className="container section-head"><div><p className="section-label">How we work</p><h2>A clear path from<br/><em>concept to launch.</em></h2></div><p>Collaborative, practical and focused on measurable outcomes.</p></div><div className="container process-grid"><article><span>01</span><h3>Discover</h3><p>We understand your users, goals, challenges and definition of success.</p></article><article><span>02</span><h3>Define</h3><p>We shape the scope, architecture, user journey and delivery roadmap.</p></article><article><span>03</span><h3>Design & build</h3><p>We create, test and refine the solution through visible milestones.</p></article><article><span>04</span><h3>Launch & grow</h3><p>We deploy, monitor, support and evolve your product with confidence.</p></article></div></section>
  <section className="why"><div className="container split"><div><p className="section-label">Why Emplementer</p><h2>We treat your idea<br/>like a product—not<br/>just a project.</h2></div><div className="why-list"><div><b>01</b><span><strong>Business-first thinking</strong><small>Technology decisions grounded in your real goals.</small></span></div><div><b>02</b><span><strong>One accountable partner</strong><small>A connected team from discovery through maintenance.</small></span></div><div><b>03</b><span><strong>Quality without complexity</strong><small>Clean, secure solutions that remain easy to operate.</small></span></div><div><b>04</b><span><strong>Partnership that continues</strong><small>Support and improvement long after launch day.</small></span></div></div></div></section>
  <section className="faq"><div className="container"><p className="section-label">Frequently asked questions</p><h2>Before we get started.</h2><div className="faq-grid"><details><summary>What types of projects do you take on?</summary><p>We build websites, web and mobile applications, custom software, portals, e-commerce platforms, AI automation and system integrations.</p></details><details><summary>Can you build from an early-stage idea?</summary><p>Yes. We help clarify requirements, prioritise features and create a realistic roadmap before design and development begin.</p></details><details><summary>Do you support products after launch?</summary><p>Yes. We offer maintenance, monitoring, performance improvement, feature development and ongoing technical support.</p></details><details><summary>How do I receive a project estimate?</summary><p>Share your idea, current challenge and desired outcome. After a discovery conversation, we provide a proposed scope, timeline and cost estimate.</p></details></div></div></section>
  <section id="contact" className="contact"><div className="container contact-inner"><p className="section-label">Have an idea?</p><h2>Let’s turn it into<br/><span>something real.</span></h2><p>Tell us what you want to build. We’ll help you find the clearest path from idea to implementation.</p><a className="button primary" href="mailto:contact@emplementer.com?subject=Project enquiry for Emplementer">contact@emplementer.com <span>↗</span></a></div></section>
  <footer><div className="container footer-top"><img src="/logo-emplementer.png" alt="Emplementer"/><p>We code. We build.<br/><span>We implement.</span></p></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Emplementer. All rights reserved.</span><div><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></div></div></footer>
</main> }
